### ISSUE TITLE
goss binary and tests should be cleaned up after tests run

### ISSUE THREAD

**Issue by fishnix** [YaleUniversity/packer-provisioner-goss#1]

**Comment by EleanorRigby** [comment]
No work should be required for this.. i guess

As long as everything happens in /tmp, it should be fine. As soon as OS is restarted (starting an ami/OVA...) it will clear off /tmp.

What do you think?

**Comment by EleanorRigby** [comment]
No work should be required for this.. i guess

As long as everything happens in /tmp, it should be fine. As soon as OS is restarted (starting an ami/OVA...) it will clear off /tmp.

What do you think?

**Comment by fishnix** [comment]
I think you're probably right.
