### ISSUE TITLE
release 0.2.0 is out of sync with the current codebase

### ISSUE THREAD

**Issue by vamegh** [YaleUniversity/packer-provisioner-goss#10]
Hi @fishnix, 

I just tried the 0.2.0 release that you put up and it doesn't seem like any of the changes have been applied to it. 

I made a new release here: 

https://github.com/vamegh/packer-provisioner-goss/releases/tag/v0.2.0

using the following script: 

```
#!/usr/bin/env bash

package=$1
if [[ -z "$package" ]]; then
  echo "usage: $0 <package-name>"
  exit 1
fi
package_split=(${package//\// })
package_name=${package_split[-1]}

platforms=("windows/amd64" "windows/386" "darwin/amd64" "darwin/386" "linux/amd64" "linux/386")

for platform in "${platforms[@]}"
do
    platform_split=(${platform//\// })
    GOOS=${platform_split[0]}
    GOARCH=${platform_split[1]}
    output_name=$package_name'-'$GOOS'-'$GOARCH
    if [ $GOOS = "windows" ]; then
        output_name+='.exe'
    fi

    env GOOS=$GOOS GOARCH=$GOARCH go build -o $output_name $package
    if [ $? -ne 0 ]; then
        echo 'An error has occurred! Aborting the script execution...'
        exit 1
    fi
done
```

From: https://www.digitalocean.com/community/tutorials/how-to-build-go-executables-for-multiple-platforms-on-ubuntu-16-04

These now support all of the new features, if you could can you please update the binaries for the release to match the current state of the code.

**Comment by fishnix** [comment]
Ah! I see what happened -- I pointed at your repo for testing when you opened your PR and built from `master` there instead of here.  Updating now.
