### ISSUE TITLE
Install Documentation: additional info

### ISSUE THREAD

**Issue by mschuchard** [YaleUniversity/packer-provisioner-goss#13]
In the steps for installing the plugin, it should be noted that if the plugin is placed at `~/.packer.d/plugins/packer-provisioner-goss`, then it requires to also have user executable permissions. Otherwise, packer throws an error of

> error initializing provisioner 'goss': fork/exec /usr/bin/packer-provisioner-goss: no such file or directory

which is easily discernable as requiring the permission change, but still absent from the install steps in the doc. I am not sure how best to word this absent step for installation, so I am opening an issue instead of a PR.

**Comment by fishnix** [comment]
Thanks for reporting this!
