### ISSUE TITLE
goss_file vs tests is confusing

### ISSUE THREAD

**Issue by caarlos0** [YaleUniversity/packer-provisioner-goss#16]
so, as far as I understand, `tests` only copies the given files to the machine, but the tests that are actually execute is whatever is defined on `goss_file`, right?

so, even if tests is an array, I can only run 1 suite.

maybe we can remove `goss_file` and run all the suites given on `tests`?

if you agree, I can work on a patch for it...

thanks for the project BTW :)

**Comment by caarlos0** [comment]
I actually have a version of this working on my fork...

**Comment by oz123** [comment]
@fishnix This is actually quite useful to have this. Would you accept a PR for this?

**Comment by fishnix** [comment]
closing old issues, reopen if still interested 👍
