### ISSUE TITLE
Provisioner type not found error when using packer with goss

### ISSUE THREAD

**Issue by nurilgft** [YaleUniversity/packer-provisioner-goss#19]
I am using packer version 1.4.4 on windows. I have put the packer-provisioner-goss file in APPDATA/packer.d/plugins and also in the directory where packer is installed however I get this error:

- building
Failed to initialize build 'googlecompute': provisioner type not found: goss
googlecompute output will be in this color.

==> Builds finished but no artifacts were created.

How can this issue be resolved.

**Comment by an-sush** [comment]
I have the same issue

**Comment by GennadySpb** [comment]
@an-sush @nurilgft try to run Packer with env variable PACKER_LOG like

`PACKER_LOG=1 packer build template.json`

**Comment by fishnix** [comment]
closing old issues, reopen if still interested 👍
