### ISSUE TITLE
Packer API Version 5 fix instructions 

### ISSUE THREAD

**Issue by pedroMMM** [YaleUniversity/packer-provisioner-goss#20]
Since this project seems a state I have a fix for the Packer API Version 5 error if anyone needs it.

The error is:
> error initializing provisioner ‘goss’: Incompatible API version with plugin. Plugin version: 4, Ours: 5

My fix: https://github.com/pedroMMM/packer-provisioner-goss/pull/4

**Comment by GennadySpb** [comment]
@pedroMMM Hi! Please make PR to this repo. 

@fishnix Please, check this issue. Without update from @pedroMMM there is impossible to use this  provisioner with Packer 1.5+

**Comment by fishnix** [comment]
Thanks folks, created PR #21

**Comment by karanveersingh5623** [comment]
Hi Guys , I am still facing this issue 
root@sriov-kvm:~/.terraform.d/plugins/projects/terraform/terraform-libvirt-ubuntu-examples/test/packer/cloud-data# packer build -force xen.json
Failed to initialize build 'xenserver-iso': error initializing builder 'xenserver-iso': Incompatible API version with plugin. Plugin version: 4, Ours: 5

==> Builds finished but no artifacts were created.
