### ISSUE TITLE
binary release

### ISSUE THREAD

**Issue by dominikborkowski** [YaleUniversity/packer-provisioner-goss#23]
Hello,

Are there any plans to bring back the binaries for new releases? This would cut down on an additional step when preparing packer stack.

Thanks!

**Comment by virgofx** [comment]
ping @fishnix Any chance we can get binaries for 1.5?

**Comment by fishnix** [comment]
sure, I will get a binary release out soon 👍

**Comment by dominikborkowski** [comment]
Thanks! My attempts to build it failed, partially because the Docker container used by Hashicorp to build Packer itself is using an older version of Go, which doesn't support modules. If you can also post build requirements/instructions, it will make it easier to create a build container and pull results out of it later on.

Cheers!

**Comment by fishnix** [comment]
Hi - I've added the build binaries to the v1.0.0 release.  Thanks!
