### ISSUE TITLE
Need automated build for binaries

### ISSUE THREAD

**Issue by fishnix** [YaleUniversity/packer-provisioner-goss#34]
Opening for comments, not looking for PRs at this time for this Issue.

I would like to setup a github action to automatically build and deploy this project on release.  In other projects, I'm using [wangyoucao577/go-release-action](https://github.com/wangyoucao577/go-release-action) and would like to continue using the same action but it will result in compressed binaries that would need to be uncompressed after download.

Would this cause a problem for where you are using this provisioner?

**Comment by fishnix** [comment]
@EleanorRigby

**Comment by EleanorRigby** [comment]
@fishnix : Will this also apply to old binaries? 

If this is just for new binaries from henceforth, I can add an extra step to unzip/untar and then place it in `~/.packer.d/plugins`

**Comment by EleanorRigby** [comment]
Is it also possible for you to open maintenance and more admin role for this repo to folks outside `YaleUniversity`. I can help shoulder some release and review work if you are interested.

**Comment by fishnix** [comment]
Hi @EleanorRigby -

It would definitely *not* apply to old binaries, just new ones after the current release.

I don't know if it's possible to allow other folks into the repo honestly, but I can try to find out.  I'm happy to have other eyes on any PRs that come through though if you're interested in doing some of that as well.  Automating the build and upload of binaries will make the process quite a bit less tedious. 😄 

Thanks for the input and PRs!

**Comment by fishnix** [comment]
Heads up @EleanorRigby - v2.0.0 will have compressed binary releases

**Comment by EleanorRigby** [comment]
@fishnix : I tried release 1.4.0, it seems the binaries are not packaged right. It gives exec error. Can you check?

**Comment by fishnix** [comment]
Did you try release `v2.0.0` or `v1.4.0` ?  I didn't upload any binaries for `v1.4.0`... maybe that's the issue?

**Comment by EleanorRigby** [comment]
Now trying v2.0.0 , seems to work well. Thanks for your help.

**Comment by fishnix** [comment]
glad to hear it! 👍
