### ISSUE TITLE
No test error details during packer build

### ISSUE THREAD

**Issue by mieel** [YaleUniversity/packer-provisioner-goss#48]
Im running a packer build on MacOs, targeting a vSphere instance.

In my goss.yaml a deliberately misspelled a version to fail the test.

When building the template, the process fails as expected, but I'm not getting the goss output:

```
    vsphere-clone: goss version v0.3.9
==> vsphere-clone: Uploading goss tests...
    vsphere-clone: Creating directory: /tmp/goss
    vsphere-clone: Uploading goss/goss.yml
==> vsphere-clone: 
==> vsphere-clone: 
==> vsphere-clone: 
==> vsphere-clone: Running goss tests...
==> vsphere-clone: Running GOSS render command: cd /tmp/goss &&  /tmp/goss-0.3.9-linux-amd64    render > /tmp/goss-spec.yaml
==> vsphere-clone: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vsphere-clone: Power off VM...
==> vsphere-clone: Destroying VM...
Build 'vsphere-clone' errored after 5 minutes 26 seconds: Error running Goss: goss non-zero exit status
```

So I know the tests failed, but it does not tell me where or what...
I've tried use the format, format_options keys, but nothing helps..

How do I get the usual output like from the `goss validate command` in the packer output?

**Comment by ccrockatt** [comment]
We're also seeing this issue and unfortunately the build takes 20 minutes so it is difficult to experiment with due to the long time to get feedback.
