### ISSUE TITLE
packer validate breaks with unknown configuration key

### ISSUE THREAD

**Issue by dominikborkowski** [YaleUniversity/packer-provisioner-goss#51]
Hello,

I'm trying to move from packer-provisioner-goss 1.4.0 to 3.0.3, and packer 1.6.x to 1.7.2. It seems that there are two config options that do not pass packer's validate function:

```
2 errors occurred:
	* unknown configuration key: '"downloadPath"'
	* unknown configuration key: '"skipInstall"'
```

To see if anything else causes issues, I used the sample config, and the above two options seem to be the only ones. The errors above are a result of using this in packer.json:

```
         {
            "type": "goss",
            "format": "tap",
            "tests": [
                "{{ template_dir }}/goss/build.yml"
            ],
	    "arch": "amd64",
    	    "downloadPath": "/tmp/goss-VERSION-linux-ARCH",
    	    "inspect": "{{user `inspect_mode`}}",
	    "password": "",
	    "skipInstall": false,
	    "url":"https://github.com/aelsabbahy/goss/releases/download/vVERSION/goss-linux-ARCH",
	    "username": "",
	    "version": "0.3.2",
            "goss_file": "build.yml"
        },
```

Am I missing something by any chance? Thanks!

**Comment by kkeshavamurthy** [comment]
I'm running into this error too.

**Comment by kkeshavamurthy** [comment]
I think the keys to use in the newer version are

```
download_path
skip_install
```

**Comment by dominikborkowski** [comment]
@kkeshavamurthy : thanks! Changing the option names fixed it.
