### ISSUE TITLE
PR Proposal: update to latest Packer SDK and modern plugin support

### ISSUE THREAD

**Issue by mschuchard** [YaleUniversity/packer-provisioner-goss#62]
I wanted to gauge interest in a PR for updating to the latest Packer SDK and enabling modern plugin support for this repository. It would be helpful for various projects if we could use the GoSS provisioner with modern Packer usage.

Please let me know. Alternatively, I can fork this project and perform light maintenance it if there is no further interest. Thanks!

**Comment by FalcoSuessgott** [comment]
This has been solved by #69
