### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by petemounce** [YaleUniversity/packer-provisioner-goss#8]
Hi there - this looks incredibly useful. I'm trying to get it to work on macOS.

I wonder if you would be willing to accept a PR that improves the README to illustrate how to get up and running?

It looks like packer needs a (platform-specific) binary of the plugin in one of several search paths: https://www.packer.io/docs/extending/plugins.html

That implies there's a platform specific build available for macOS. How're you publishing releases? Happy to try to augment that if it's simple.

**Comment by petemounce** [comment]
So, I was able to 

```
go get github.com/YaleUniversity/packer-provisioner-goss
cp bin/packer-provisioner-goss <my packer working directory on my mac>
packer build ....
```

and I have goss tests running as my final provisioner. Which I'm really happy about; thank you again. ❤️

**Comment by fishnix** [comment]
👍
